[build]
rustflags = [
    "--cfg=web_sys_unstable_apis",
    "-C",
    "target-feature=+atomics,+bulk-memory,+mutable-globals",
    # "-C",
    # "link-arg=--max-memory=4294967296",
]

[unstable]
build-std = ["panic_abort", "std"]
